/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 capybara-transformed.glb --transform --simplify 
Files: capybara-transformed.glb [29.7MB] > /Users/nataliechoo/CSclasses/174C-Term-Project/3JS-Project/assets/capybara/capybara-transformed-transformed.glb [1.8MB] (94%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/capybara-transformed-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.back_legs.geometry} material={materials['back legs']} />
      <mesh geometry={nodes['eyes_&_snout'].geometry} material={materials['eyes & snout']} />
      <mesh geometry={nodes.nostrils.geometry} material={materials.nostrils} />
      <mesh geometry={nodes.snot.geometry} material={materials.snot} />
      <mesh geometry={nodes.body.geometry} material={materials.body} />
      <mesh geometry={nodes.front_legs.geometry} material={materials['front legs']} />
    </group>
  )
}

useGLTF.preload('/capybara-transformed-transformed.glb')
