/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 capy-edited-in-blender.glb --transform --simplify 
Files: capy-edited-in-blender.glb [15.4MB] > /Users/nataliechoo/CSclasses/174C-Term-Project/3JS-Project/assets/capybara/capy-edited-in-blender-transformed.glb [1.59MB] (90%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/capy-edited-in-blender-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.back_legs.geometry} material={materials['back legs']} />
      <mesh geometry={nodes['eyes_&_snout'].geometry} material={materials['eyes & snout']} />
      <mesh geometry={nodes.nostrils.geometry} material={materials.nostrils} />
      <mesh geometry={nodes.snot.geometry} material={materials.snot} />
      <mesh geometry={nodes.body.geometry} material={materials.body} />
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} />
    </group>
  )
}

useGLTF.preload('/capy-edited-in-blender-transformed.glb')
