/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 foundation-base2.glb --transform --simplify 
Files: foundation-base2.glb [27.86MB] > /Users/nataliechoo/CSclasses/174C-Term-Project/3JS-Project/assets/new-base/foundation-base2-transformed.glb [1.93MB] (93%)
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/foundation-base2-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" position={[121.105, 114.591, -231.133]} rotation={[-1.571, 0.043, 1.575]} scale={17.661}>
          <group name="Bone" />
          <mesh name="Area_(1)" geometry={nodes['Area_(1)'].geometry} material={materials['Area (1)']} position={[-0.046, -0.002, 0.011]} rotation={[1.528, 0, 0]} scale={0.025} />
        </group>
        <mesh name="new-walls" geometry={nodes['new-walls'].geometry} material={materials['new-walls']} position={[7.857, 184.06, -137.849]} scale={[0.447, 0.445, 0.445]} />
        <mesh name="plant" geometry={nodes.plant.geometry} material={materials.plant} position={[-23, 182.06, 179.859]} scale={0.445} />
        <mesh name="stuff" geometry={nodes.stuff.geometry} material={materials.stuff} position={[4.84, 92.06, 109.859]} scale={0.445} />
        <mesh name="base" geometry={nodes.base.geometry} material={materials.base} position={[-51, 200.06, 102.676]} scale={[0.445, 0.445, 0.467]} />
        <mesh name="baked-goods" geometry={nodes['baked-goods'].geometry} material={materials['baked-goods']} position={[-61, 80.06, 41.333]} scale={0.445} />
        <mesh name="Plane" geometry={nodes.Plane.geometry} material={nodes.Plane.material} position={[128.731, 140.018, -19.219]} rotation={[0, 0, -Math.PI / 2]} scale={[-127.573, -189.87, -218.717]} />
      </group>
    </group>
  )
}

useGLTF.preload('/foundation-base2-transformed.glb')
