/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 assets/capybara/capybara.glb --transform --simplify 
Files: assets/capybara/capybara.glb [21.85MB] > /home/shelbypop/CSC174C_ANIMATION/174C-Term-Project/3JS-Project/capybara-transformed.glb [1.79MB] (92%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/capybara-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.model_0.geometry} material={materials['model_0.006']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.model_1.geometry} material={materials['model_1.004']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.model_2.geometry} material={materials['model_2.003']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.model_3.geometry} material={materials['model_3.003']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.model_4.geometry} material={materials['model_4.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.model_6.geometry} material={materials['model_6.002']} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/capybara-transformed.glb')
