/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 assets/cup/cup.glb --transform --simplify 
Files: assets/cup/cup.glb [8.21MB] > /home/shelbypop/CSC174C_ANIMATION/174C-Term-Project/3JS-Project/cup-transformed.glb [580.98KB] (93%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/cup-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.model_0.geometry} material={materials['model_0.007']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.model_1.geometry} material={materials['model_1.005']} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/cup-transformed.glb')
