/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 assets/long-table/long_table.glb --transform --simplify 
Files: assets/long-table/long_table.glb [548.52KB] > /home/shelbypop/CSC174C_ANIMATION/174C-Term-Project/3JS-Project/long_table-transformed.glb [31.6KB] (94%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/long_table-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.model_0.geometry} material={materials.model_0} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/long_table-transformed.glb')
