/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 assets/miffy-glb/miffy.glb --transform --simplify 
Files: assets/miffy-glb/miffy.glb [18.79MB] > /home/shelbypop/CSC174C_ANIMATION/174C-Term-Project/3JS-Project/miffy-transformed.glb [1.5MB] (92%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/miffy-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} />
      <mesh geometry={nodes.model_0.geometry} material={materials.model_0} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.model_1.geometry} material={materials.model_1} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.model_2.geometry} material={materials.model_2} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.model_3.geometry} material={materials.model_3} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.model_6.geometry} material={materials.model_6} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/miffy-transformed.glb')
