/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 assets/small-table/small_table.glb --transform --simplify 
Files: assets/small-table/small_table.glb [3.54MB] > /home/shelbypop/CSC174C_ANIMATION/174C-Term-Project/3JS-Project/small_table-transformed.glb [244.2KB] (93%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/small_table-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.model_0.geometry} material={materials['model_0.004']} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/small_table-transformed.glb')
