/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 assets/star/star.glb --transform --simplify 
Files: assets/star/star.glb [370.77KB] > /home/shelbypop/CSC174C_ANIMATION/174C-Term-Project/3JS-Project/star-transformed.glb [26.94KB] (93%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/star-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.model_0001.geometry} material={materials['model_0.005']} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/star-transformed.glb')
