/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 assets/teapot/teapot.glb --transform --simplify 
Files: assets/teapot/teapot.glb [2.04MB] > /home/shelbypop/CSC174C_ANIMATION/174C-Term-Project/3JS-Project/teapot-transformed.glb [188.74KB] (91%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/teapot-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.model_0.geometry} material={materials['model_0.006']} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/teapot-transformed.glb')
