/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 donut.glb --transform --simplify 
Files: donut.glb [2.36MB] > /Users/nataliechoo/CSclasses/174C-Term-Project/3JS-Project/assets/donut/donut-transformed.glb [232.82KB] (90%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/donut-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['baked-goods'].geometry} material={materials['baked-goods']} />
    </group>
  )
}

useGLTF.preload('/donut-transformed.glb')
