/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 stool.glb --transform --simplify 
Files: stool.glb [2.59MB] > /Users/nataliechoo/CSclasses/174C-Term-Project/3JS-Project/assets/stool/stool-transformed.glb [180.15KB] (93%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/stool-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.stuff.geometry} material={materials.stuff} />
    </group>
  )
}

useGLTF.preload('/stool-transformed.glb')
