/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 moon.glb --transform --simplify 
Files: moon.glb [3.12MB] > /Users/nataliechoo/CSclasses/174C-Term-Project/3JS-Project/assets/moon/moon-transformed.glb [223.73KB] (93%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/moon-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.moon.geometry} material={materials.moon} />
    </group>
  )
}

useGLTF.preload('/moon-transformed.glb')
