/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 bubble-edited-alot.glb --transform --simplify 
Files: bubble-edited-alot.glb [8.82MB] > /Users/nataliechoo/CSclasses/174C-Term-Project/3JS-Project/assets/thought-bubble/bubble-edited-alot-transformed.glb [1.04MB] (88%)
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/bubble-edited-alot-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Empty" position={[0, 162.178, 0]} scale={97.126}>
          <group name="Empty001" position={[0, -0.936, -0.179]} scale={0.01}>
            <mesh name="trail1" geometry={nodes.trail1.geometry} material={materials.trail1} position={[0.75, 2.161, -0.595]} />
          </group>
          <group name="Empty002" position={[-0.019, -1.043, -0.424]} scale={0.01}>
            <mesh name="trail2" geometry={nodes.trail2.geometry} material={materials.trail2} position={[-1.467, -0.958, -1.404]} />
          </group>
          <mesh name="mainbubble" geometry={nodes.mainbubble.geometry} material={materials.mainbubble} position={[-0.08, -0.145, 0.038]} scale={0.01}>
            <mesh name="croissant-1741832261122" geometry={nodes['croissant-1741832261122'].geometry} material={materials['croissant-1741832261122']} position={[7.797, -148.088, -3.675]} />
            <mesh name="donut-1741832277752" geometry={nodes['donut-1741832277752'].geometry} material={materials['donut-1741832277752']} position={[7.797, -148.088, -3.675]} />
          </mesh>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/bubble-edited-alot-transformed.glb')
