/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 miffy-wave3.glb --transform --simplify 
Files: miffy-wave3.glb [35.83MB] > /Users/nataliechoo/CSclasses/174C-Term-Project/3JS-Project/assets/miffy-animation/miffy-wave3-transformed.glb [3.86MB] (89%)
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/miffy-wave3-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" position={[17.127, 37.284, -8.158]} rotation={[0.442, -0.571, 0.979]} scale={[-53.119, -24.245, -45.97]}>
          <primitive object={nodes.BoneR} />
        </group>
        <primitive object={nodes.BoneL} />
        <mesh name="head001" geometry={nodes.head001.geometry} material={materials['model_0.001']} position={[-1.434, 54.497, -5.093]} rotation={[Math.PI / 2, 0, 0]} scale={0.369} />
        <mesh name="eyes001" geometry={nodes.eyes001.geometry} material={materials['model_1.001']} position={[-2.309, 51.293, 13.178]} rotation={[Math.PI / 2, 0, 0]} scale={0.369} />
        <mesh name="mouth001" geometry={nodes.mouth001.geometry} material={materials['model_2.001']} position={[-2.909, 46.636, 14.909]} rotation={[Math.PI / 2, 0, 0]} scale={0.369} />
        <mesh name="body001" geometry={nodes.body001.geometry} material={materials['model_3.001']} position={[-1.5, 23.595, -4.464]} rotation={[Math.PI / 2, 0, 0]} scale={0.369} />
        <mesh name="ears001" geometry={nodes.ears001.geometry} material={materials['model_6.001']} position={[-0.972, 82.954, -12.568]} rotation={[Math.PI / 2, 0, 0]} scale={0.369} />
        <mesh name="R_arm001" geometry={nodes.R_arm001.geometry} material={materials['model_5.001']} />
        <skinnedMesh name="R_arm" geometry={nodes.R_arm.geometry} material={materials.model_5} skeleton={nodes.R_arm.skeleton} position={[17.127, 37.284, -8.158]} rotation={[-2.699, 0.571, -0.979]} scale={[-53.119, 24.245, 45.97]} />
        <skinnedMesh name="L_arm" geometry={nodes.L_arm.geometry} material={materials.model_5} skeleton={nodes.L_arm.skeleton} position={[-15.155, 33.905, -6.51]} rotation={[2.792, 0.102, 0.844]} scale={[-43.685, 19.943, 37.805]} />
      </group>
    </group>
  )
}

useGLTF.preload('/miffy-wave3-transformed.glb')
