/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 miffy-wave-fixed-arms.glb --transform --simplify 
Files: miffy-wave-fixed-arms.glb [19.52MB] > /Users/nataliechoo/CSclasses/174C-Term-Project/3JS-Project/assets/miffy-animation/miffy-wave-fixed-arms-transformed.glb [2.01MB] (90%)
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/miffy-wave-fixed-arms-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" position={[11.113, 35.489, -7.633]} rotation={[0, 0, -2.453]} scale={18.685}>
          <primitive object={nodes.Bone} />
        </group>
        <primitive object={nodes.neutral_bone} />
        <mesh name="head" geometry={nodes.head.geometry} material={materials.model_0} position={[-1.434, 54.497, -5.093]} rotation={[Math.PI / 2, 0, 0]} scale={0.369} />
        <mesh name="eyes" geometry={nodes.eyes.geometry} material={materials.model_1} position={[-2.309, 51.293, 13.178]} rotation={[Math.PI / 2, 0, 0]} scale={0.369} />
        <mesh name="body" geometry={nodes.body.geometry} material={materials.model_3} position={[-1.5, 23.595, -4.464]} rotation={[Math.PI / 2, 0, 0]} scale={0.369} />
        <skinnedMesh name="R_arm" geometry={nodes.R_arm.geometry} material={materials.model_3} skeleton={nodes.R_arm.skeleton} position={[11.113, 35.489, -7.633]} rotation={[0, 0, -2.453]} scale={18.685} />
      </group>
    </group>
  )
}

useGLTF.preload('/miffy-wave-fixed-arms-transformed.glb')
