/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 teapot-transformed.glb --transform --simplify 
Files: teapot-transformed.glb [188.74KB] > /Users/nataliechoo/CSclasses/174C-Term-Project/3JS-Project/assets/teapot/teapot-transformed-transformed.glb [109.8KB] (42%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/teapot-transformed-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.model_0.geometry} material={materials['model_0.006']} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/teapot-transformed-transformed.glb')
