/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 textured-sign.glb --transform --simplify 
Files: textured-sign.glb [23.6MB] > /Users/nataliechoo/CSclasses/174C-Term-Project/3JS-Project/assets/sign/textured-sign-transformed.glb [906.25KB] (96%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/textured-sign-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Area_(1)'].geometry} material={materials['Area (1)']} />
      <mesh geometry={nodes['Area_(2)'].geometry} material={materials['Area (2)']} position={[-48.182, 46.109, -17.698]} rotation={[1.913, 0, 0]} />
      <mesh geometry={nodes.S.geometry} material={materials.S} />
    </group>
  )
}

useGLTF.preload('/textured-sign-transformed.glb')
