/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 croissant.glb --transform --simplify 
Files: croissant.glb [2.39MB] > /Users/nataliechoo/CSclasses/174C-Term-Project/3JS-Project/assets/croissant/croissant-transformed.glb [216.11KB] (91%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/croissant-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['baked-goods'].geometry} material={materials['baked-goods']} />
    </group>
  )
}

useGLTF.preload('/croissant-transformed.glb')
