/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 tray.glb --transform --simplify 
Files: tray.glb [2.54MB] > /Users/nataliechoo/CSclasses/174C-Term-Project/3JS-Project/assets/tray/tray-transformed.glb [158.74KB] (94%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/tray-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Area_(2)'].geometry} material={materials['Area (2)']} />
    </group>
  )
}

useGLTF.preload('/tray-transformed.glb')
