/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 plant.glb --transform --simplify 
Files: plant.glb [6.19MB] > /Users/nataliechoo/CSclasses/174C-Term-Project/3JS-Project/assets/plant/plant-transformed.glb [750.87KB] (88%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/plant-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.plant.geometry} material={materials.plant} />
      <mesh geometry={nodes['Area_(2)'].geometry} material={materials['Area (2)']} />
    </group>
  )
}

useGLTF.preload('/plant-transformed.glb')
