/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 sign-animation-combined.glb --transform --simplify 
Files: sign-animation-combined.glb [3.95MB] > /Users/nataliechoo/CSclasses/174C-Term-Project/3JS-Project/assets/sign-animation-test/sign-animation-combined-transformed.glb [548.62KB] (86%)
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/sign-animation-combined-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Torus072" geometry={nodes.Torus072.geometry} material={nodes.Torus072.material} position={[0.023, 15.873, 0.01]} rotation={[0, -0.001, 0]}>
          <mesh name="Torus001" geometry={nodes.Torus001.geometry} material={nodes.Torus001.material} position={[-0.026, -2.522, -0.61]} rotation={[-2.856, 1.549, 3.067]} />
          <mesh name="Torus002" geometry={nodes.Torus002.geometry} material={nodes.Torus002.material} position={[-0.027, -3.34, -0.9]} rotation={[-2.93, -0.022, 3.14]} />
          <mesh name="Torus050" geometry={nodes.Torus050.geometry} material={nodes.Torus050.material} position={[-2.564, -0.864, -0.233]} rotation={[-2.856, 1.549, 3.067]} />
          <mesh name="Torus051" geometry={nodes.Torus051.geometry} material={nodes.Torus051.material} position={[-2.562, -1.728, -0.412]} rotation={[-2.93, -0.022, 3.14]} />
          <mesh name="Torus053" geometry={nodes.Torus053.geometry} material={nodes.Torus053.material} position={[-2.561, -2.54, -0.587]} rotation={[-2.856, 1.549, 3.067]} />
          <mesh name="Torus056" geometry={nodes.Torus056.geometry} material={nodes.Torus056.material} position={[-2.558, -3.42, -0.733]} rotation={[-2.93, -0.022, 3.14]} />
          <mesh name="Torus058" geometry={nodes.Torus058.geometry} material={nodes.Torus058.material} position={[-2.557, -4.255, -0.926]} rotation={[-2.856, 1.549, 3.067]} />
          <mesh name="Torus059" geometry={nodes.Torus059.geometry} material={nodes.Torus059.material} position={[-2.555, -5.168, -1.108]} rotation={[-2.93, -0.022, 3.14]} />
          <mesh name="Torus060" geometry={nodes.Torus060.geometry} material={nodes.Torus060.material} position={[-2.554, -5.984, -1.283]} rotation={[-2.856, 1.549, 3.067]} />
          <mesh name="Torus061" geometry={nodes.Torus061.geometry} material={nodes.Torus061.material} position={[-0.021, -5.937, -1.395]} rotation={[-2.856, 1.549, 3.067]} />
          <mesh name="Torus062" geometry={nodes.Torus062.geometry} material={nodes.Torus062.material} position={[-0.022, -5.121, -1.22]} rotation={[-2.93, -0.022, 3.14]} />
          <mesh name="Torus063" geometry={nodes.Torus063.geometry} material={nodes.Torus063.material} position={[-0.024, -4.165, -1.014]} rotation={[-2.856, 1.549, 3.067]} />
          <mesh name="Torus070" geometry={nodes.Torus070.geometry} material={nodes.Torus070.material} position={[-0.029, -1.681, -0.524]} rotation={[-2.93, -0.022, 3.14]} />
          <mesh name="Torus071" geometry={nodes.Torus071.geometry} material={nodes.Torus071.material} position={[-0.028, -0.863, -0.234]} rotation={[-2.856, 1.549, 3.067]} />
          <mesh name="Torus074" geometry={nodes.Torus074.geometry} material={materials['model_0.002']} position={[-2.552, -6.754, -1.443]} rotation={[-2.93, -0.022, 3.14]} />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/sign-animation-combined-transformed.glb')
