/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 sign-animation-combined2.glb --transform --simplify 
Files: sign-animation-combined2.glb [3.81MB] > /Users/nataliechoo/CSclasses/174C-Term-Project/3JS-Project/assets/sign-animation-test/sign-animation-combined2-transformed.glb [416.19KB] (89%)
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/sign-animation-combined2-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Empty" position={[-1.266, 18.316, 0]}>
          <mesh name="Torus001" geometry={nodes.Torus001.geometry} material={nodes.Torus001.material} position={[0.022, -2.445, -0.589]} rotation={[-2.827, 1.551, 3.038]} />
          <mesh name="Torus002" geometry={nodes.Torus002.geometry} material={nodes.Torus002.material} position={[0.022, -3.263, -0.879]} rotation={[-2.93, -0.02, 3.14]} />
          <mesh name="Torus050" geometry={nodes.Torus050.geometry} material={nodes.Torus050.material} position={[-2.517, -0.787, -0.217]} rotation={[-2.827, 1.551, 3.038]} />
          <mesh name="Torus051" geometry={nodes.Torus051.geometry} material={nodes.Torus051.material} position={[-2.515, -1.651, -0.397]} rotation={[-2.93, -0.02, 3.14]} />
          <mesh name="Torus053" geometry={nodes.Torus053.geometry} material={nodes.Torus053.material} position={[-2.513, -2.462, -0.571]} rotation={[-2.827, 1.551, 3.038]} />
          <mesh name="Torus056" geometry={nodes.Torus056.geometry} material={nodes.Torus056.material} position={[-2.51, -3.342, -0.717]} rotation={[-2.93, -0.02, 3.14]} />
          <mesh name="Torus058" geometry={nodes.Torus058.geometry} material={nodes.Torus058.material} position={[-2.509, -4.178, -0.91]} rotation={[-2.827, 1.551, 3.038]} />
          <mesh name="Torus059" geometry={nodes.Torus059.geometry} material={nodes.Torus059.material} position={[-2.506, -5.091, -1.093]} rotation={[-2.93, -0.02, 3.14]} />
          <mesh name="Torus060" geometry={nodes.Torus060.geometry} material={nodes.Torus060.material} position={[-2.505, -5.906, -1.268]} rotation={[-2.827, 1.551, 3.038]} />
          <mesh name="Torus061" geometry={nodes.Torus061.geometry} material={nodes.Torus061.material} position={[0.028, -5.859, -1.374]} rotation={[-2.827, 1.551, 3.038]} />
          <mesh name="Torus062" geometry={nodes.Torus062.geometry} material={nodes.Torus062.material} position={[0.027, -5.044, -1.199]} rotation={[-2.93, -0.02, 3.14]} />
          <mesh name="Torus063" geometry={nodes.Torus063.geometry} material={nodes.Torus063.material} position={[0.024, -4.088, -0.993]} rotation={[-2.827, 1.551, 3.038]} />
          <mesh name="Torus070" geometry={nodes.Torus070.geometry} material={nodes.Torus070.material} position={[0.018, -1.604, -0.503]} rotation={[-2.93, -0.02, 3.14]} />
          <mesh name="Torus071" geometry={nodes.Torus071.geometry} material={nodes.Torus071.material} position={[0.019, -0.786, -0.213]} rotation={[-2.827, 1.551, 3.038]} />
          <mesh name="Torus074" geometry={nodes.Torus074.geometry} material={materials['model_0.002']} position={[-2.503, -6.676, -1.427]} rotation={[-2.93, -0.02, 3.14]} />
          <mesh name="Torus072" geometry={nodes.Torus072.geometry} material={nodes.Torus072.material} position={[1.289, -2.443, 0.01]} rotation={[0, -0.001, 0]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/sign-animation-combined2-transformed.glb')
