/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 sign-animation.glb --transform --simplify 
Files: sign-animation.glb [3.81MB] > /Users/nataliechoo/CSclasses/174C-Term-Project/3JS-Project/assets/sign-animation-test/sign-animation-transformed.glb [415.31KB] (89%)
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/sign-animation-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Torus072" geometry={nodes.Torus072.geometry} material={nodes.Torus072.material} position={[0.023, 15.873, 0.01]} rotation={[0, -0.001, 0]}>
          <mesh name="Torus001" geometry={nodes.Torus001.geometry} material={nodes.Torus001.material} position={[-0.002, -2.483, -0.6]} rotation={[-2.842, 1.55, 3.054]} />
          <mesh name="Torus002" geometry={nodes.Torus002.geometry} material={nodes.Torus002.material} position={[-0.003, -3.302, -0.89]} rotation={[-2.93, -0.021, 3.14]} />
          <mesh name="Torus050" geometry={nodes.Torus050.geometry} material={nodes.Torus050.material} position={[-2.54, -0.825, -0.225]} rotation={[-2.842, 1.55, 3.054]} />
          <mesh name="Torus051" geometry={nodes.Torus051.geometry} material={nodes.Torus051.material} position={[-2.538, -1.69, -0.405]} rotation={[-2.93, -0.021, 3.14]} />
          <mesh name="Torus053" geometry={nodes.Torus053.geometry} material={nodes.Torus053.material} position={[-2.537, -2.501, -0.579]} rotation={[-2.842, 1.55, 3.054]} />
          <mesh name="Torus056" geometry={nodes.Torus056.geometry} material={nodes.Torus056.material} position={[-2.534, -3.381, -0.725]} rotation={[-2.93, -0.021, 3.14]} />
          <mesh name="Torus058" geometry={nodes.Torus058.geometry} material={nodes.Torus058.material} position={[-2.533, -4.217, -0.918]} rotation={[-2.842, 1.55, 3.054]} />
          <mesh name="Torus059" geometry={nodes.Torus059.geometry} material={nodes.Torus059.material} position={[-2.531, -5.129, -1.1]} rotation={[-2.93, -0.021, 3.14]} />
          <mesh name="Torus060" geometry={nodes.Torus060.geometry} material={nodes.Torus060.material} position={[-2.529, -5.945, -1.276]} rotation={[-2.842, 1.55, 3.054]} />
          <mesh name="Torus061" geometry={nodes.Torus061.geometry} material={nodes.Torus061.material} position={[0.004, -5.898, -1.384]} rotation={[-2.842, 1.55, 3.054]} />
          <mesh name="Torus062" geometry={nodes.Torus062.geometry} material={nodes.Torus062.material} position={[0.002, -5.082, -1.209]} rotation={[-2.93, -0.021, 3.14]} />
          <mesh name="Torus063" geometry={nodes.Torus063.geometry} material={nodes.Torus063.material} position={[0, -4.127, -1.004]} rotation={[-2.842, 1.55, 3.054]} />
          <mesh name="Torus070" geometry={nodes.Torus070.geometry} material={nodes.Torus070.material} position={[-0.005, -1.643, -0.514]} rotation={[-2.93, -0.021, 3.14]} />
          <mesh name="Torus071" geometry={nodes.Torus071.geometry} material={nodes.Torus071.material} position={[-0.005, -0.824, -0.223]} rotation={[-2.842, 1.55, 3.054]} />
          <mesh name="Torus074" geometry={nodes.Torus074.geometry} material={materials['model_0.002']} position={[-2.528, -6.715, -1.435]} rotation={[-2.93, -0.021, 3.14]} />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/sign-animation-transformed.glb')
