/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 oven.glb --transform --simplify 
Files: oven.glb [9.5MB] > /Users/nataliechoo/CSclasses/174C-Term-Project/3JS-Project/assets/oven/oven-transformed.glb [893.03KB] (91%)
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/oven-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" position={[-0.068, 0, -34.291]} rotation={[-1.636, -0.018, -0.018]} scale={14.167}>
          <group name="Bone" />
          <mesh name="lid" geometry={nodes.lid.geometry} material={materials.lid} position={[0.029, -0.286, 0.099]} rotation={[1.646, 0.017, -0.019]} scale={0.071} />
        </group>
        <mesh name="oven" geometry={nodes.oven.geometry} material={materials['oven.001']} position={[0, 22.842, 0]} />
        <mesh name="metals" geometry={nodes.metals.geometry} material={materials['metals.001']} position={[-0.029, 4.203, -14.407]} />
        <mesh name="conductor" geometry={nodes.conductor.geometry} material={materials.conductor} position={[1.04, 0.414, -14.946]} />
      </group>
    </group>
  )
}

useGLTF.preload('/oven-transformed.glb')
