/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 cloud2.glb --transform --simplify 
Files: cloud2.glb [2.42MB] > /Users/nataliechoo/CSclasses/174C-Term-Project/3JS-Project/assets/cloud-animation/cloud2-transformed.glb [185.12KB] (92%)
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/cloud2-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="cloud" geometry={nodes.cloud.geometry} material={materials.cloud} position={[-135.352, 70.317, -221.423]} />
      </group>
    </group>
  )
}

useGLTF.preload('/cloud2-transformed.glb')
