/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 capysleepin.glb --transform --simplify 
Files: capysleepin.glb [13.41MB] > /Users/nataliechoo/CSclasses/174C-Term-Project/3JS-Project/assets/capybara-sleeping/capysleepin-transformed.glb [1.31MB] (90%)
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/capysleepin-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Empty" position={[-53.006, 108.898, 0]} scale={195.725}>
          <mesh name="body" geometry={nodes.body.geometry} material={materials.BL} position={[0.161, 0.007, -0.034]} scale={0.005} />
          <mesh name="snot" geometry={nodes.snot.geometry} material={materials.snot} position={[1.128, -0.412, -0.138]} scale={0.005} />
        </group>
        <mesh name="BL" geometry={nodes.BL.geometry} material={materials.BL} />
      </group>
    </group>
  )
}

useGLTF.preload('/capysleepin-transformed.glb')
