/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 base2.glb --transform --simplify 
Files: base2.glb [2.8MB] > /Users/nataliechoo/CSclasses/174C-Term-Project/3JS-Project/assets/base&window/base2-transformed.glb [241.82KB] (91%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/base2-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.base.geometry} material={materials.base} scale={0.1} />
    </group>
  )
}

useGLTF.preload('/base2-transformed.glb')
