/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 colored-base.glb --transform --simplify 
Files: colored-base.glb [2.75MB] > /Users/nataliechoo/CSclasses/174C-Term-Project/3JS-Project/assets/base&window/colored-base-transformed.glb [241.67KB] (91%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/colored-base-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.base.geometry} material={materials.base} />
    </group>
  )
}

useGLTF.preload('/colored-base-transformed.glb')
